### ISSUE TITLE
Argument syntax may need to be changed because of SE-0066

### ISSUE THREAD

**Issue by Abizern** [soffes/Cache#1]
Swift Evolution 66 https://github.com/apple/swift-evolution/blob/master/proposals/0066-standardize-function-type-syntax.md will require arguments to be placed in parameters.

There are parts that will need to be changed, and it's better to do it now, rather than later.

e.g.

```
func get(key key: String, completion: (Element? -> Void))
```

should be

   func get(key key: String, completion: ((Element?) -> Void))

Just putting this here for discussion, I'll take a stab at it if no one else wants to.

**Comment by calebd** [comment]
I would prefer dropping the outer parenthesis. `func get(key key: String, completion: (Element?) -> ())`

**Comment by Abizern** [comment]
Good point - that does look better. Thanks.

**Comment by Abizern** [comment]
I'm going to hold off on this. Just trying to build on the latest toolchain causes more warnings and errors that this Issue covers.
